//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentStorePaymentMethod
    {
        public GatewayPaymentStorePaymentMethod()
        {
            this.GatewayPaymentOrder = new HashSet<GatewayPaymentOrder>();
        }
    
        public System.Guid UniqueId { get; set; }
        public System.Guid GatewayPaymentStore { get; set; }
        public Nullable<bool> PaymentMethodDefault { get; set; }
        public Nullable<System.Guid> GatewayPaymentMethodTypeJoin { get; set; }
    
        public virtual GatewayPaymentMethodTypeJoin GatewayPaymentMethodTypeJoin1 { get; set; }
        public virtual ICollection<GatewayPaymentOrder> GatewayPaymentOrder { get; set; }
        public virtual GatewayPaymentStore GatewayPaymentStore1 { get; set; }
    }
}
