//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentUser
    {
        public GatewayPaymentUser()
        {
            this.GatewayPaymentToken = new HashSet<GatewayPaymentToken>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int UserCode { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public System.Guid GatewayPaymentStore { get; set; }
        public System.Guid GatewayPaymentPosition { get; set; }
    
        public virtual GatewayPaymentPosition GatewayPaymentPosition1 { get; set; }
        public virtual GatewayPaymentStore GatewayPaymentStore1 { get; set; }
        public virtual ICollection<GatewayPaymentToken> GatewayPaymentToken { get; set; }
    }
}
