//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentApp
    {
        public GatewayPaymentApp()
        {
            this.GatewayPaymentAccount = new HashSet<GatewayPaymentAccount>();
        }
    
        public System.Guid UniqueId { get; set; }
        public string Appid { get; set; }
        public string Appkey { get; set; }
    
        public virtual ICollection<GatewayPaymentAccount> GatewayPaymentAccount { get; set; }
    }
}
