//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentPosition
    {
        public GatewayPaymentPosition()
        {
            this.GatewayPaymentUser = new HashSet<GatewayPaymentUser>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int PositionID { get; set; }
        public string PositionName { get; set; }
    
        public virtual ICollection<GatewayPaymentUser> GatewayPaymentUser { get; set; }
    }
}
