//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GatewayPayEntities : DbContext
    {
        public GatewayPayEntities()
            : base("name=GatewayPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GatewayPaymentAccount> GatewayPaymentAccount { get; set; }
        public DbSet<GatewayPaymentApp> GatewayPaymentApp { get; set; }
        public DbSet<GatewayPaymentMethod> GatewayPaymentMethod { get; set; }
    }
}
