//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentStore
    {
        public System.Guid UniqueId { get; set; }
        public int StoreId { get; set; }
        public System.Guid GatewayPaymentAccount { get; set; }
        public string StoreName { get; set; }
    
        public virtual GatewayPaymentAccount GatewayPaymentAccount1 { get; set; }
    }
}
