//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentAccount
    {
        public GatewayPaymentAccount()
        {
            this.GatewayPaymentStore = new HashSet<GatewayPaymentStore>();
        }
    
        public System.Guid UniqueId { get; set; }
        public string Appid { get; set; }
        public string Mchid { get; set; }
        public string Mchkey { get; set; }
        public string MchPublickey { get; set; }
        public string Publickey { get; set; }
        public System.Guid GatewayPaymentApp { get; set; }
        public System.Guid GatewayPaymentMethod { get; set; }
        public string Name { get; set; }
    
        public virtual GatewayPaymentApp GatewayPaymentApp1 { get; set; }
        public virtual GatewayPaymentMethod GatewayPaymentMethod1 { get; set; }
        public virtual ICollection<GatewayPaymentStore> GatewayPaymentStore { get; set; }
    }
}
