//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentMethodTypeJoin
    {
        public GatewayPaymentMethodTypeJoin()
        {
            this.GatewayPaymentStorePaymentMethod = new HashSet<GatewayPaymentStorePaymentMethod>();
        }
    
        public System.Guid UniqueId { get; set; }
        public System.Guid GatewayPaymentMethod { get; set; }
        public System.Guid GatewayPaymentMethodType { get; set; }
    
        public virtual GatewayPaymentMethod GatewayPaymentMethod1 { get; set; }
        public virtual GatewayPaymentMethodType GatewayPaymentMethodType1 { get; set; }
        public virtual ICollection<GatewayPaymentStorePaymentMethod> GatewayPaymentStorePaymentMethod { get; set; }
    }
}
