//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentBillAlipay
    {
        public System.Guid UniqueId { get; set; }
        public string StoreId { get; set; }
        public System.Guid GatewayPaymentMerchant { get; set; }
        public string TradeNo { get; set; }
        public string OrderNumber { get; set; }
        public string TradeType { get; set; }
        public string ProductName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string StoreNumber { get; set; }
        public string StoreName { get; set; }
        public string Operator { get; set; }
        public string Terminal { get; set; }
        public string MchAccount { get; set; }
        public string TotalAmount { get; set; }
        public string ReceiveAmount { get; set; }
        public string AlipayRPAmount { get; set; }
        public string AlipayJFAmount { get; set; }
        public string AlipayPromoAmount { get; set; }
        public string MchPromoAmount { get; set; }
        public string CouponAmount { get; set; }
        public string CouponName { get; set; }
        public string MchRPAmount { get; set; }
        public string CardAmount { get; set; }
        public string RefundNumber { get; set; }
        public string Fee { get; set; }
        public string Profit { get; set; }
        public string Note { get; set; }
        public System.DateTime TSID { get; set; }
    }
}
