//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9Pay.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPaymentOrderDetail
    {
        public System.Guid UniqueId { get; set; }
        public System.Guid GatewayPaymentOrder { get; set; }
        public string ItemName { get; set; }
        public decimal ItemQty { get; set; }
        public decimal ItemAmount { get; set; }
        public System.DateTime TSID { get; set; }
    
        public virtual GatewayPaymentOrder GatewayPaymentOrder1 { get; set; }
    }
}
